baseurl = "http://www.developeratwork.nl"
title = "Developer @ work"

theme = "hugo-coder"

languagecode = "nl"
defaultcontentlanguage = "nl"

paginate = 20
canonifyurls = true

pygmentsstyle = "b2"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

disqusShortname = "yourdiscussshortname"

[params]
    author = "Rogier Reedijk"
    description = "Rogier Reedijk = Developer @ work"
    keywords = "freelance,developer"
    info = "Freelance Fullstack .NET developer"
    avatarurl = "images/rogier.jpg"
    # footercontent = "Enter a text here."

    dateformat = "2 January 2006"

    hideCredits = false
    hideCopyright = false
    since = 2020

    # Git Commit in Footer, uncomment the line below to enable it.
    # commit = "https://github.com/luizdepra/hugo-coder/tree/"

    rtl = false

    # Specify light/dark colorscheme
    # Supported values:
    # "auto" (use preference set by browser)
    # "dark" (dark background, light foreground)
    # "light" (light background, dark foreground) (default)
    colorscheme = "auto"

    # Series see also post count
    maxSeeAlsoItems = 5

    # Custom CSS
    custom_css = []
    
    # Custom JS
    custom_js = []

[taxonomies]
  category = "categories"
  series = "series"
  tag = "tags"

[[params.social]]
    name = "LinkedIn"
    icon = "fab fa-linkedin"
    weight = 1
    url = "https://www.linkedin.com/in/rogierreedijk/"
[[params.social]]
    name = "Github"
    icon = "fab fa-github"
    weight = 2
    url = "https://github.com/xs4free/"
#[[params.social]]
#    name = "Gitlab"
#    icon = "fab fa-gitlab"
#    weight = 2
#    url = "https://gitlab.com/johndoe/"
[[params.social]]
    name = "Twitter"
    icon = "fab fa-twitter"
    weight = 3
    url = "https://twitter.com/xs4free/"
[[params.social]]
    name = "Personal blog"
    icon = "fas fa-blog"
    weight = 4
    url = "https://www.progz.nl/blog/"
#[[params.social]]
#    name = "Medium"
#    icon = "fab fa-medium"
#    weight = 5
#    url = "https://medium.com/@johndoe"
#[[params.social]]
#    name = "RSS"
#    icon = "fas fa-rss"
#    weight = 6
#    url = "https://myhugosite.com/index.xml"
#    rel = "alternate"
#    type = "application/rss+xml"


